# Generated by Django 5.1.2 on 2025-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_author_alter_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='articles',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Важная статья'),
        ),
    ]
