# Generated by Django 5.2 on 2025-04-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
